name: Bump Version on Push

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bump version in pyproject.toml
        run: |
          # Extract current version
          current_version=$(grep '^version = ' pyproject.toml | sed 's/version = "\(.*\)"/\1/')
          echo "Current version: $current_version"

          IFS='.' read -r major minor patch <<< "$current_version"

          patch=$((patch + 1))
          if [ $patch -gt 9 ]; then
            patch=0
            minor=$((minor + 1))
            if [ $minor -gt 9 ]; then
              minor=0
              major=$((major + 1))
            fi
          fi

          new_version="$major.$minor.$patch"
          echo "New version: $new_version"

          sed -i "s/version = \"$current_version\"/version = \"$new_version\"/" pyproject.toml

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pyproject.toml
          git commit -m "Bump version to $new_version"
          git push
